/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

/**
 *
 * @author Natalie Ulate Rojas
 */
public class acercaDeDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(acercaDeDialog.class.getName());

    /**
     * Creates new form acercaDeDialog
     */
    public acercaDeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        lblTituloApp = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCreditos = new javax.swing.JTextArea();
        lblLogo = new javax.swing.JLabel();
        panelBotonCierre = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelInfo.setName("panelInfo"); // NOI18N
        panelInfo.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        lblTituloApp.setBackground(new java.awt.Color(200, 162, 200));
        lblTituloApp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloApp.setText("Sistema de Caja de Cafetería UTN");
        panelInfo.add(lblTituloApp);

        lblVersion.setBackground(new java.awt.Color(200, 162, 200));
        lblVersion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("Versión 1.0");
        panelInfo.add(lblVersion);

        txtAreaCreditos.setEditable(false);
        txtAreaCreditos.setBackground(new java.awt.Color(200, 162, 200));
        txtAreaCreditos.setColumns(20);
        txtAreaCreditos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAreaCreditos.setLineWrap(true);
        txtAreaCreditos.setRows(5);
        txtAreaCreditos.setText("Desarrollado por: Natalie Ulate Rojas\nCurso: ITI Programación 1\nAño:  2025");
        txtAreaCreditos.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaCreditos);

        panelInfo.add(jScrollPane1);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-utn.png"))); // NOI18N
        panelInfo.add(lblLogo);

        getContentPane().add(panelInfo, java.awt.BorderLayout.CENTER);

        panelBotonCierre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panelBotonCierre.add(btnAceptar);

        getContentPane().add(panelBotonCierre, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloApp;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel panelBotonCierre;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JTextArea txtAreaCreditos;
    // End of variables declaration//GEN-END:variables
}
