/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

/**
 *
 * @author Natalie Ulate Rojas
 */
public class CalculadoraDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraDialog.class.getName());

    private double primerNumero;
    private String operadorActual;
    private boolean esperandoNuevoNumero;

    public CalculadoraDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.operadorActual = "";
        this.esperandoNuevoNumero = true;

        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnSigno = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");
        setName("calculadoraDialog"); // NOI18N

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtDisplay, java.awt.BorderLayout.PAGE_START);

        panelBotones.setLayout(new java.awt.GridLayout(5, 4, 5, 5));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("C");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelBotones.add(btnLimpiar);

        btnPotencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPotencia.setText("x^y");
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });
        panelBotones.add(btnPotencia);

        btnPorcentaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPorcentaje.setText("%");
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });
        panelBotones.add(btnPorcentaje);

        btnDividir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        panelBotones.add(btnDividir);

        btnSiete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSiete.setText("7");
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });
        panelBotones.add(btnSiete);

        btnOcho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOcho.setText("8");
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });
        panelBotones.add(btnOcho);

        btnNueve.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNueve.setText("9");
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });
        panelBotones.add(btnNueve);

        btnMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMultiplicar.setText("x");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        panelBotones.add(btnMultiplicar);

        btnCuatro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCuatro.setText("4");
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });
        panelBotones.add(btnCuatro);

        btnCinco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCinco.setText("5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        panelBotones.add(btnCinco);

        btnSeis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeis.setText("6");
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        panelBotones.add(btnSeis);

        btnRestar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRestar.setText("-");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        panelBotones.add(btnRestar);

        btnUno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        panelBotones.add(btnUno);

        btnDos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDos.setText("2");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });
        panelBotones.add(btnDos);

        btnTres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTres.setText("3");
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });
        panelBotones.add(btnTres);

        btnSumar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSumar.setText("+");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        panelBotones.add(btnSumar);

        btnSigno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSigno.setText("+/-");
        btnSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoActionPerformed(evt);
            }
        });
        panelBotones.add(btnSigno);

        btnCero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCero.setText("0");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });
        panelBotones.add(btnCero);

        btnPunto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        panelBotones.add(btnPunto);

        btnIgual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        panelBotones.add(btnIgual);

        getContentPane().add(panelBotones, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        agregarDigito("1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        agregarDigito("2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        agregarDigito("3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        agregarDigito("4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        agregarDigito("5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        agregarDigito("6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        agregarDigito("7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        agregarDigito("8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        agregarDigito("9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        agregarDigito("0");
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        seleccionarOperador("+");
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        seleccionarOperador("-");
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        seleccionarOperador("x");
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        seleccionarOperador("x^y");
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        seleccionarOperador("/");
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        if (operadorActual.isEmpty()) {
            return;
        }

        double segundoNumero = Double.parseDouble(txtDisplay.getText());
        double resultado = 0;

        switch (operadorActual) {
            case "+":
                resultado = primerNumero + segundoNumero;
                break;
            case "-":
                resultado = primerNumero - segundoNumero;
                break;
            case "x":
                resultado = primerNumero * segundoNumero;
                break;
            case "/":
                if (segundoNumero == 0) {
                    txtDisplay.setText("Error");
                    return;
                }
                resultado = primerNumero / segundoNumero;
                break;
            case "x^y":
                resultado = Math.pow(primerNumero, segundoNumero);
                break;
        }

        txtDisplay.setText(String.valueOf(resultado));
        operadorActual = "";
        esperandoNuevoNumero = true;
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtDisplay.setText("0");
        primerNumero = 0;
        operadorActual = "";
        esperandoNuevoNumero = true;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (!txtDisplay.getText().contains(".")) {
            agregarDigito(".");
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed
        double valorActual = Double.parseDouble(txtDisplay.getText());
        double resultado = valorActual / 100.0;
        txtDisplay.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnPorcentajeActionPerformed

    private void btnSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoActionPerformed
        try {
            String textoActual = txtDisplay.getText();
            double numeroActual = Double.parseDouble(textoActual);
            if (numeroActual != 0) {
                double numeroInvertido = numeroActual * -1;
                if (numeroInvertido == (long) numeroInvertido) {
                    txtDisplay.setText(String.format("%d", (long) numeroInvertido));
                } else {
                    txtDisplay.setText(String.valueOf(numeroInvertido));
                }
            }
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_btnSignoActionPerformed
    private void agregarDigito(String digito) {
        if (esperandoNuevoNumero) {
            txtDisplay.setText("");
            esperandoNuevoNumero = false;
        }
        if (txtDisplay.getText().equals("0") && !digito.equals(".")) {
            txtDisplay.setText(digito);
        } else {
            txtDisplay.setText(txtDisplay.getText() + digito);
        }
    }

    /**
     * Almacena el primer número y el operador seleccionado.
     */
    private void seleccionarOperador(String operador) {
        primerNumero = Double.parseDouble(txtDisplay.getText());
        operadorActual = operador;
        esperandoNuevoNumero = true;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSigno;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
